# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-05-04 11:38
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='KairiParcels',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kairi_parc', models.FloatField()),
                ('name', models.IntegerField()),
                ('owner_name', models.CharField(max_length=50)),
                ('remm_area', models.FloatField()),
                ('area', models.FloatField()),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
            ],
        ),
    ]
