# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-05-08 08:05
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acquiredarea', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Acquiredarea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('objectid', models.IntegerField()),
                ('name', models.IntegerField()),
                ('area', models.FloatField()),
                ('rem_area', models.FloatField()),
                ('shape_leng', models.FloatField()),
                ('shape_area', models.FloatField()),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
            ],
        ),
    ]
